# -*- coding: utf-8 -*-
"""dedup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aq_1Urpp91z1-qZDPsy9pSH2_tCNqyoy
"""

!pip install text-dedup

# prompt: Viết lại để chạy từ 00001 đến 00009 của train-0000{i}-of-00016.parquet của cell bên dưới


# Loop through the files
for i in range(0, 10):
  !python -m text_dedup.minhash \
   --path "/content/drive/MyDrive" \
   --split "train" \
   --data_files "train-0000"{i}"-of-00016.parquet"\
   --cache_dir "./cache" \
   --output "/content/drive/MyDrive/dedup"{i} \
   --column "text" \
   --num_perm 112\
   --threshold 0.75\
   --b 14\
   --r 8\
   --batch_size 10000